### ISSUE TITLE
ollama installer should try harder to look for existing installations

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/rancher-desktop-rdx-open-webui-archive#6]
It currently detects a running instance, but not when the app is installed but nor currently running. Some thoughts are in https://github.com/rancher-sandbox/rd-open-webui-docker-ext/discussions/2#discussioncomment-10758098.

It may be useful to create a symlink from the actual install location to `~/.ollama/ollama` in case Ollama is not already running when the extension is loaded.

That also means that just deleting `~/.ollama/ollama` on extension removal will uninstall our version, but not touch anything already installed by the user.

**Comment by mook-as** [comment]
Symlinks are not (usefully) a thing on Windows.

Proposed install behaviour:
- Make the installer executable have a mode (subcommand) that searches for ollama in some hard-coded list of locations and return the first found, or nothing if not found.
- On the initial screen, if that returns ollama not being found, instead show an installation screen where the user can (optionally) choose an install location, plus a button to start the installation.  If the user doesn't choose anything, we will install into the extension directory (instead of `~/.ollama/ollama` as the current default).
- When doing the actual installation, write the installed location to a file in the extension directory. (This file is to be consulted in step 1 and used as the preferred location.)
- Under this flow, we do _not_ use the post-install hook.

Proposed uninstall behaviour:
- We use the pre-uninstall hook to terminate ollama and delete the files.
- The location is found via reading the installed location file (step 3 of the install process).
- For now, do not remove the models. If we do that, it will be an additional PR on top of what is described here.

Other notes:
- We will ignore `~/.ollama/ollama` (that is, the current install location) as the extension isn't public yet, and expect people who have already tried this to delete it manually.

Thoughts?

**Comment by jandubois** [comment]
Trying the extension on Linux.

Ollama is installed via `curl -fsSL https://ollama.com/install.sh | sh`.

It is running as a service using the `ollama` account by default and can be stopped/restarted with `sudo systemctl stop ollama.service`.

The models and certs are installed in `/usr/share/ollama/.ollama`. Everything is only readable by the `ollama` user:

```
drwx------ 1 ollama ollama 178 Oct  1 15:59 /usr/share/ollama/
```

When I load the extension page, it **always** says "Ollama needs to be installed", even though it will use the running instance after I click "Install":

<img width="318" alt="CleanShot 2024-10-02 at 15 09 59@2x" src="https://github.com/user-attachments/assets/fdcc0646-1dd0-4352-9762-06859581d55d">

This page comes up every single time when I switch away and back to the extension.

It needs to correctly determine that Ollama is installed (or running), and then not prompt.

When I stop the ollama service and run the extension, it will run its own instance under the current user. It won't have access to the existing certs and models, and will create `~/.ollama` instead, downloading the models again.

Maybe this is unavoidable, at least for a v1 release, and we can refine this later.

I found the "Install Ollama to custom location" setting confusing. It will always install to a custom location because the default location is typically not writable for us. Maybe it should say "Choose Ollama install location", and explain that otherwise we'll install into a location that will be removed when the extension is removed.

Also, I haven't tested it, but I assume if I pick an install location where Ollama is already installed, it will use that location and not overwrite it, right?

**Comment by jandubois** [comment]
Superseded by #10
